name: Staging CI/CD

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
    types: [closed]

env:
  IMAGE_NAME: reyshazni/${{github.event.repository.name}}
  CONTAINER_NAME: ${{github.event.repository.name}}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PORT: 8080

jobs:
  dockerize-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build --platform linux/amd64 -t $(echo ${{ IMAGE_NAME }}) .

      - name: Push the Docker image
        run: docker push $(echo $IMAGE_NAME)

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: dockerize-and-push

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ IP_STAGING }}
          username: root
          script: |
            # Pull image
            docker pull ${{ IMAGE_NAME }}
            # Stop running container
            docker stop ${{ CONTAINER_NAME }}
            # Remove old container
            docker rm ${{ CONTAINER_NAME }}
            # Remove dangling image
            docker image prune -a
            yes | head -1
            # Run image and open port
            docker run -d -p 80:${{ PORT }} --name ${{ CONTAINER_NAME }} ${{ IMAGE_NAME }}